model: inversion_recovery
inversion_times:
- 350.0
- 500.0
- 650.0
- 800.0
- 950.0
- 1100.0
- 1250.0
- 1400.0
- 1700.0
method: magnitude
t1_range:
  start: 1
  stop: 5000
  step: 1
zoom:
  iterations: 2
  points: 21
