#!/usr/bin/env python3
"""Generate the MyST model pages from `qmrust catalog`.

Every model page, the model gallery, and the landing page's card grid are
written from the catalog alone. This script knows no model names: add a model
to the Rust registry, regenerate, and its page appears.

    ./target/release/qmrust catalog > catalog.json
    python3 scripts/gen_model_docs.py --catalog catalog.json

`--check` regenerates into a temporary tree and diffs it against the committed
pages, exiting non-zero on any difference. That is the CI gate that keeps the
pages honest.
"""
import argparse
import difflib
import json
import pathlib
import posixpath
import re
import sys

GENERATED_BY = "scripts/gen_model_docs.py"
HEADER = (
    f"<!-- Generated by {GENERATED_BY}. Do not edit by hand.\n"
    "     Regenerate: qmrust catalog > catalog.json &&\n"
    f"                 python3 {GENERATED_BY} --catalog catalog.json -->"
)
GALLERY_BEGIN = "<!-- BEGIN generated: model gallery -->"
GALLERY_END = "<!-- END generated: model gallery -->"
GITHUB = "https://github.com/qmrlab/qmrust/blob/main"
FIGURE_NAMES = ("inputs", "aux", "outputs", "curve")


class GenError(Exception):
    """A generation input is inconsistent — always fatal, never a warning."""


# --- small helpers ----------------------------------------------------------

def num(v):
    """Format a protocol value compactly: 0.35 not 0.35000000000000003."""
    return f"{v:g}"


def identity_labels(model):
    """One label per acquired volume, from the identities the model reads."""
    meas = model["measurement"]
    if meas["kind"] == "named":
        return [r["role"] for r in meas["roles"]]
    return [", ".join(f"{k}={num(v)}" for k, v in row.items()) for row in meas["rows"]]


def bound(v):
    return "unbounded" if v is None else num(v)


def unit(u):
    return u if u else "—"


def read(repo_root, rel):
    p = repo_root / rel
    if not p.exists():
        raise GenError(f"declared file does not exist: {rel}")
    return p.read_text().rstrip("\n")


# --- blocks -----------------------------------------------------------------

def render_frontmatter(model, figures):
    lines = [
        "---",
        f"title: {model['title']}",
        f"subtitle: {model['category_title']} · BIDS suffix {model['bids_suffix']}",
        "keywords:",
        f"  - {model['category_title']}",
        f"  - {model['bids_suffix']}",
    ]
    if "outputs" in figures:
        lines.append(f"thumbnail: {figures['outputs']}")
    lines.append("---")
    return "\n".join(lines)


def render_identity(model):
    rows = [
        ("Config name", f"`model: {model['name']}`"),
        ("BIDS suffix", f"`{model['bids_suffix']}`"),
        ("Method family", model["category_title"]),
        ("Acquired volumes", str(model["n_volumes"])),
        ("Fit granularity", model["strategy"]),
    ]
    out = []
    for k, v in rows:
        out.append(f"{k}\n: {v}")
    return "\n".join(out)


def render_equation(model):
    body = [
        "## Signal model",
        "",
        "```{math}",
        f":label: eq-{model['name']}",
        model["equation"],
        "```",
        "",
        "| Symbol | Quantity | Unit |",
        "|---|---|---|",
    ]
    for s in model["symbols"]:
        body.append(f"| `{s['name']}` | {s['meaning']} | {unit(s['unit'])} |")
    return "\n".join(body)


def render_acquisition(model):
    meas = model["measurement"]
    body = ["## What the model reads", ""]
    if meas["kind"] == "named":
        body += [
            f"A fixed set of {len(meas['roles'])} role-labeled volumes. Order "
            "does not matter — each volume is matched to its role by its "
            "BIDS filename entities.",
            "",
            "| Role | Entities |",
            "|---|---|",
        ] + [
            "| `{}` | {} |".format(
                r["role"],
                ", ".join(f"`{e['key']}-{e['value']}`" for e in r["entities"]),
            )
            for r in meas["roles"]
        ]
    else:
        keys = sorted({k for row in meas["rows"] for k in row})
        body += [
            f"A series of {len(meas['rows'])} volumes indexed by "
            + ", ".join(f"`{k}`" for k in keys)
            + ". Volumes are matched to these identities by value, so "
            "reordering the acquisition yields an identical fit.",
            "",
            "| # | " + " | ".join(keys) + " |",
            "|---|" + "---|" * len(keys),
        ]
        for i, row in enumerate(meas["rows"], start=1):
            body.append(f"| {i} | " + " | ".join(num(row[k]) for k in keys) + " |")

    if model["protocol_schema"]:
        srcs = {"field": "sidecar field", "derived": "derived from sidecar metadata",
                "option": "config option"}
        scopes = {"per_volume": "per volume", "global": "whole collection"}
        body += [
            "",
            "### Where the protocol comes from",
            "",
            "In a BIDS dataset these values are resolved for you:",
            "",
            "| Protocol parameter | Source | Key | Resolved |",
            "|---|---|---|---|",
        ]
        for p in model["protocol_schema"]:
            key = f"`{p['key']}`" if p["key"] else "—"
            body.append(
                f"| `{p['name']}` | {srcs[p['source']]} | {key} "
                f"| {scopes[p['scope']]} |"
            )
    return "\n".join(body)


def render_inputs_figure(model, figures):
    if "inputs" not in figures and "aux" not in figures:
        return ""
    body = ["## Inputs", ""]
    if "inputs" in figures:
        body += [
            "```{figure} " + figures["inputs"],
            f":label: fig-{model['name']}-inputs",
            f"The {model['n_volumes']} acquired volumes, each labeled with the "
            "identity the model reads it by.",
            "```",
            "",
        ]
    if "aux" in figures:
        body += [
            "```{figure} " + figures["aux"],
            f":label: fig-{model['name']}-aux",
            "Auxiliary maps and the mask applied to this fit.",
            "```",
            "",
        ]
    return "\n".join(body).rstrip()


def render_aux_table(model):
    if not model["required_inputs"]:
        return ""
    body = [
        "### Auxiliary maps",
        "",
        "| Input | Required | BIDS suffix | CLI flag |",
        "|---|---|---|---|",
    ]
    for i in model["required_inputs"]:
        suffix = f"`{i['bids_suffix']}`" if i["bids_suffix"] else "—"
        flag = f"`--{i['name'].lower()}`"
        body.append(
            f"| `{i['name']}` | {'yes' if i['required'] else 'optional'} "
            f"| {suffix} | {flag} |"
        )
    return "\n".join(body)


def render_outputs_table(model):
    quant = [o for o in model["outputs"] if not o["diagnostic"]]
    diag = [o for o in model["outputs"] if o["diagnostic"]]
    bounds = {p["name"]: p for p in model["params"]}
    body = [
        "## Outputs",
        "",
        "| Map | BIDS suffix | Unit | Fit bounds | Fitted |",
        "|---|---|---|---|---|",
    ]
    for o in quant:
        p = bounds.get(o["name"])
        rng = (
            f"{bound(p['lower'])} … {bound(p['upper'])}" if p else "—"
        )
        fitted = "—" if not p else ("fixed" if p["fixed"] else "free")
        body.append(
            f"| `{o['name']}` | `{o['bids_suffix']}` | {unit(o['unit'])} "
            f"| {rng} | {fitted} |"
        )
    if diag:
        body += [
            "",
            ":::{dropdown} Diagnostic outputs",
            "Written alongside the quantitative maps, but not quantitative "
            "measurements — they describe the fit, not the tissue.",
            "",
            "| Output |",
            "|---|",
        ] + [f"| `{o['name']}` |" for o in diag] + [":::"]
    return "\n".join(body)


def render_outputs_figure(model, figures):
    if "outputs" not in figures:
        return ""
    return "\n".join([
        "```{figure} " + figures["outputs"],
        f":label: fig-{model['name']}-outputs",
        "Fitted maps for one example subject.",
        "```",
    ])


def render_usage(model, repo_root):
    r = model["recipes"]
    name = model["name"]
    aux_flags = "".join(
        f" \\\n  --{i['name'].lower()} <file>" for i in model["required_inputs"]
    )
    tabs = [
        "## Usage",
        "",
        "::::{tab-set}",
        ":::{tab-item} BIDS",
        ":sync: bids",
        "",
        f"The acquisition comes from the sidecars, so `{r['bids']}` carries "
        "only algorithm options:",
        "",
        "```yaml",
        read(repo_root, r["bids"]),
        "```",
        "",
        "```bash",
        f"qmrust fit --bids-dir ds-mydata \\",
        f"  --config {r['bids']} --output-dir out",
        "```",
        "",
        "Fitted maps are written as BIDS derivatives:",
        "",
        "```text",
        "out/derivatives/qmrust/sub-01/anat/",
    ]
    for o in model["outputs"]:
        if not o["diagnostic"]:
            tabs.append(f"  sub-01_{o['bids_suffix']}.nii.gz")
            tabs.append(f"  sub-01_{o['bids_suffix']}.json")
    tabs += [
        "```",
        ":::",
        "",
        ":::{tab-item} Without BIDS",
        ":sync: non-bids",
        "",
        f"No sidecars, so `{r['non_bids']}` declares the acquisition itself:",
        "",
        "```yaml",
        read(repo_root, r["non_bids"]),
        "```",
        "",
        "```bash",
        "qmrust fit --data data.nii.gz --mask mask.nii.gz \\",
        f"  --config {r['non_bids']}{aux_flags} \\",
        "  --output-dir out",
        "```",
        "",
        "See [Fitting without BIDS](../../guide/non-bids.md).",
        ":::",
    ]
    if r["sim"]:
        tabs += [
            "",
            ":::{tab-item} Simulation",
            ":sync: sim",
            "",
            "```yaml",
            read(repo_root, r["sim"]),
            "```",
            "",
            "```bash",
            f"qmrust sim signal       --config {r['sim']} --output signal.json",
            f"qmrust sim single-voxel --config {r['sim']} --output sv.json",
            f"qmrust sim sensitivity  --config {r['sim']} --output sens.json",
            f"qmrust sim montecarlo   --config {r['sim']} --output mc.json",
            "```",
            "",
            "See [Simulation](../../guide/simulation.md).",
            ":::",
        ]
    tabs += [
        "",
        ":::{tab-item} Browser",
        ":sync: wasm",
        "",
        "The same core, compiled to WebAssembly:",
        "",
        "```js",
        "import init, { fit_volume } from './pkg/qmrust_wasm.js';",
        "await init();",
        "const maps = fit_volume(configYaml, data, [nx, ny, nz, nt],",
        "                        JSON.stringify(volumeIds), mask, '{}');",
        "```",
        "",
        f"Try it on real data in the [playground](../../playground.md), or read "
        "[Browser & wasm](../../guide/browser.md).",
        ":::",
        "::::",
    ]
    return "\n".join(tabs)


def render_curve_figure(model, figures):
    if "curve" not in figures:
        return ""
    named = model["measurement"]["kind"] == "named"
    caption = (
        "Measured values for one voxel beside the model's forward prediction "
        "at the fitted parameters."
        if named else
        "One voxel's measured data with the model's forward signal at the "
        "fitted parameters. The curve is computed by the same Rust code that "
        "does the fitting."
    )
    return "\n".join([
        "```{figure} " + figures["curve"],
        f":label: fig-{model['name']}-curve",
        caption,
        "```",
    ])


def render_implementation(model):
    src = model["source_dir"]
    body = [
        "## Implementation",
        "",
        f"- [`model.rs`]({GITHUB}/{src}/model.rs) — the `Model` implementation: "
        "measurement contract, protocol schema, BIDS outputs.",
        f"- [`fit.rs`]({GITHUB}/{src}/fit.rs) — the numerical fit.",
        f"- [`config.rs`]({GITHUB}/{src}/config.rs) — configuration and validation.",
        "",
        ":::{dropdown} Fully-resolved configuration",
        "Every default materialized, as `qmrust dump-config` prints it.",
        "",
        "```yaml",
        model["effective_config"].rstrip("\n"),
        "```",
        ":::",
    ]
    return "\n".join(body)


def render_references(model):
    keys = " ".join(f"@{k}" for k in model["citations"])
    return "\n".join(["## References", "", keys])


def render_page(model, figures, repo_root):
    blocks = [
        render_frontmatter(model, figures),
        HEADER,
        render_identity(model),
        model["summary"],
        render_equation(model),
        render_acquisition(model),
        render_inputs_figure(model, figures),
        render_aux_table(model),
        render_outputs_table(model),
        render_outputs_figure(model, figures),
        render_usage(model, repo_root),
        render_curve_figure(model, figures),
        render_implementation(model),
        render_references(model),
    ]
    return "\n\n".join(b for b in blocks if b) + "\n"


def render_gallery(models, prefix, heading_level=3):
    """Card grid, grouped by category. `prefix` prefixes each card's link.

    `heading_level` must match the heading depth of the section the gallery
    is spliced into, one level below it, so MyST sees an unbroken hierarchy.
    """
    marker = "#" * heading_level
    out = []
    seen = []
    for m in models:
        if m["category"] not in [c for c, _ in seen]:
            seen.append((m["category"], m["category_title"]))
    for slug, title in seen:
        group = [m for m in models if m["category"] == slug]
        out += [f"{marker} {title}", "", "::::{grid} 1 1 2 2"]
        for m in group:
            out += [
                ":::{card}",
                f":header: {m['title']}",
                f":link: {prefix}{slug}/{m['name']}.md",
                "",
                m["summary"].split(". ")[0] + ".",
                "",
                f"`{m['bids_suffix']}` · "
                + ", ".join(
                    f"`{o['bids_suffix']}`" for o in m["outputs"]
                    if not o["diagnostic"]
                ),
                ":::",
            ]
        out += ["::::", ""]
    return "\n".join(out).rstrip()


def render_gallery_index(models):
    return "\n\n".join([
        HEADER,
        "# Methods",
        "Every model qmrust fits, grouped by method family. Each page documents "
        "what the model reads, what it produces, and how to run it with and "
        "without BIDS.",
        render_gallery(models, prefix="", heading_level=2),
    ]) + "\n"


# --- validation and writing -------------------------------------------------

def validate_citations(models, bib_path):
    if not bib_path.exists():
        raise GenError(f"bibliography not found: {bib_path}")
    keys = set(re.findall(r"@\w+\{([^,]+),", bib_path.read_text()))
    for m in models:
        for c in m["citations"]:
            if c not in keys:
                raise GenError(
                    f"{m['name']}: citation key '{c}' is not in {bib_path.name}"
                )


def find_figures(repo_root, model_name, page_dir):
    """Map figure kind -> path relative to the page, for figures that exist."""
    found = {}
    for kind in FIGURE_NAMES:
        abs_path = repo_root / "docs" / "figures" / model_name / f"{kind}.webp"
        if abs_path.exists():
            found[kind] = posixpath.relpath(
                f"figures/{model_name}/{kind}.webp", page_dir
            )
    return found


def splice_gallery(text, gallery):
    if GALLERY_BEGIN not in text or GALLERY_END not in text:
        raise GenError(
            "docs/index.md is missing the gallery markers "
            f"{GALLERY_BEGIN} / {GALLERY_END}"
        )
    head, rest = text.split(GALLERY_BEGIN, 1)
    _, tail = rest.split(GALLERY_END, 1)
    return f"{head}{GALLERY_BEGIN}\n{gallery}\n{GALLERY_END}{tail}"


def generate(models, repo_root):
    """All generated files as {repo-relative path: content}."""
    files = {}
    for m in models:
        page_dir = f"models/{m['category']}"
        figures = find_figures(repo_root, m["name"], page_dir)
        files[f"docs/{page_dir}/{m['name']}.md"] = render_page(m, figures, repo_root)
    files["docs/models/index.md"] = render_gallery_index(models)
    index = repo_root / "docs" / "index.md"
    if index.exists():
        files["docs/index.md"] = splice_gallery(
            index.read_text(), render_gallery(models, prefix="models/")
        )
    return files


def write_all(models, repo_root, check=False):
    files = generate(models, repo_root)
    if check:
        drift = []
        for rel, content in files.items():
            existing = repo_root / rel
            actual = existing.read_text() if existing.exists() else ""
            if actual != content:
                drift.append(rel)
                sys.stderr.write(
                    "".join(difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        content.splitlines(keepends=True),
                        fromfile=f"committed/{rel}", tofile=f"generated/{rel}",
                    ))
                )
        if drift:
            raise GenError(
                "generated documentation is out of date:\n  "
                + "\n  ".join(drift)
                + "\n\nRegenerate with: qmrust catalog > catalog.json && "
                f"python3 {GENERATED_BY} --catalog catalog.json"
            )
        return
    for rel, content in files.items():
        path = repo_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--catalog", required=True, type=pathlib.Path)
    ap.add_argument("--repo-root", default=".", type=pathlib.Path)
    ap.add_argument("--check", action="store_true",
                    help="fail if committed pages differ from generated ones")
    args = ap.parse_args(argv)

    models = json.loads(args.catalog.read_text())["models"]
    try:
        validate_citations(models, args.repo_root / "docs" / "references.bib")
        write_all(models, args.repo_root, check=args.check)
    except GenError as e:
        sys.stderr.write(f"error: {e}\n")
        return 1
    action = "checked" if args.check else "wrote"
    print(f"{action} {len(models)} model pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
